
services:
  - type: web
    name: whatsapp-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: META_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
